spring:
  application:
    name: testSpring

  datasource:
    url: jdbc:postgresql://localhost:5432/crm
    username: codekitchen
    password: 12345678

    hikari:
      maximum-pool-size: 8
  jpa:
    hibernate:
      ddl-auto: none
server:
  port: 9090